# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMbayes <- function(x, alpha = 0, beta = 0, lambda = 0, eps = 1e-8, verbose = TRUE) {
    .Call(`_SDS2020_EMbayes`, x, alpha, beta, lambda, eps, verbose)
}

